import "./globals.css";
import "./fanta.css";
import Head from "./head";
import Link from "next/link";
import Cart from "@/components/Cart";
import EmailInput from "@/components/EmailInput";


export const metadata = {
  title: "Anvit's Store",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head />
      <body >
        <div id ="portal" />
        <div id="app">
          <header>
            <div className="header-content">
              <Link href={'/'}>
                <h1>AnvitStore</h1> 
              </Link>

              <h5 className="mid-text">- Cool stuff for cool people -</h5>
               <Cart/>
            </div>
          </header>
          <main>
            {children}
          </main>
          <div className="hr" />
          <footer>
            <div className="email-container">
              <h5>Get a sneak peak at new additions to the store, special offers, and so much more.</h5>
              <EmailInput/>
            </div>

            <div className="liks-container">
              <div>
                <h3>AnvitSingh</h3>
                <Link href={'/'}>Project 1</Link>
                <Link href={'/'}>Project 2</Link>
              </div>
              <div>
                <h3>Store</h3>
                <Link href={'/'}>Home</Link>
                <Link href={'/cart'}>Cart</Link>
              </div>
              <div>
                <h3>Support</h3>
                <Link href={'/contact'}>Contact</Link>
                <Link href={'/faq'}>FAQs</Link>
              </div>
            </div>

            <div className="socials">
            <p>© <a href="https://www.anvitdoestech.com" target="_blank">Anvit Singh</a> 2025<br />Built with NextJS  🔥</p>
                <div className="social-links">
                  <Link href={'/'} target="_blank"><i className="fa-brands fa-github"></i></Link>
                  <Link href={'/'} target="_blank"><i className="fa-brands fa-youtube"></i></Link>
                  <Link href={'/'} target="_blank"><i className="fa-brands fa-linkedin"></i></Link>
                </div>
            </div>
            
          </footer>   
        </div>
      </body>
    </html>
  );
}
